#!/usr/bin/env python

import os
from os import makedirs
from shutil import rmtree
import subprocess
import logging
import logging.handlers
from optparse import OptionParser
import string
from ksl.install.installer import installer

def main():
    (options, args) = get_options()
    setup_installer_log(options)
    installer_variants = parse_install_file(options, args)
    for variant in installer_variants:
        try:
            variant_logs = []
            if variant.build_host != os.uname()[4]:
                log = logging.getLogger('ksl.installer')
                log.info('skipping variant %s because it requires build arch %s [host arch: %s]' %
                         (variant.variant_id, variant.build_host, os.uname()[4]))
                continue

            setup_target_dir(variant, options)
            variant_logs = setup_package_logs(variant)
            variant.install()
            close_logs(variant_logs)

        except Exception, err:
            log = logging.getLogger('ksl.installer')
            log.error('error during install of variant %s: %s', (variant.variant_id, err))
            close_logs(variant_logs)        

def get_options():
    parser = OptionParser()
    parser.add_option("-q", "--quiet",
                      action="store_false", dest="verbose", default=True,
                      help="silence informational status messages")
    parser.add_option("-f", "--force",
                      action="store_true", dest="force", default=False,
                      help="clobber target directories and files")
    parser.add_option("-r", "--root",
                      action="store", dest="root", default="/opt/share/ksl",
                      help="root directory to install to (default: /opt/share/ksl)")
    parser.add_option("-s", "--source_paths",
                      action="store", dest="source_paths",
                      default="/opt/share/ksl/system/sources",
                      help="source paths to search " +\
                      "(default: /opt/share/ksl/systems/sources)")
    parser.add_option("-p", "--patch_paths",
                      action="store", dest="patch_paths",
                      default="/opt/share/ksl/system/patches",
                      help="patch paths to search " +\
                      "(default: /opt/share/ksl/systems/patches)")
    parser.add_option("-b", "--build_dir",
                      action="store", dest="build_dir", default="./kslbuild",
                      help="working build directory (default: ./klsbuild)")
    parser.add_option("-m", "--module_cmd",
                      action="store", dest="module_cmd",
                      default="/opt/share/ksl/tools/Modules/3.2.7/bin/modulecmd",
                      help="module command " + \
                      "(default: /opt/share/ksl/tools/Modules/3.2.7/bin/modulecmd)")

    (options, args) = parser.parse_args()

    if not args:
        raise Exception("You forget to specify an install file!")
    return (options, args)

def setup_installer_log(options):

    if options.verbose:
        logging.basicConfig(level=logging.INFO,
                            format='%(message)s')
    else:
        logging.basicConfig(level=logging.WARNING,
                            format='%(message)s')
    
    # ten backup files at 100MB for a total of ~1GB potential logs 
    syslog = logging.handlers.RotatingFileHandler('/opt/share/ksl/system/logs/ksl_install.log',
                                                  mode='a',
                                                  maxBytes=104857600,
                                                  backupCount=10)
    syslog.setLevel(logging.DEBUG)
    syslogf = logging.Formatter('%(asctime)s %(name)-12s %(levelname)-8s %(message)s', '%m-%d %H:%M')
    syslog.setFormatter(syslogf)
    
    logging.getLogger('ksl.installer').addHandler(syslog)


def setup_target_dir(variant, options):
    variant.target_dir = join(
        variant.root,variant.name,variant.version,variant.variant_id)
    
    if os.path.exists(variant.target_dir):
        if not options.force:
            confirmation = raw_input(
                "Can I clobber target directory %s? [y/n]: " % variant.target_dir)
            
            if confirmation is not 'y':
                raise Exception(
                    "unwilling to clobber target directory %s" % variant.target_dir)
            
        rmtree(variant.target_dir)

    makedirs(variant.target_dir)


def setup_package_logs(variant):
    root = '/opt/share/ksl/system/logs/installs'
    prefix = variant.name+'-'+variant.version+'-'+variant.release+'_'+variant.variant_id

    logf = logging.Formatter('%(asctime)s %(name)s:\n%(message)s')

    logname = join(root,prefix+'_install.log')
    plog = logging.FileHandler(logname,'w')
    plog.setFormatter(logf)
    
    logging.getLogger('ksl.installer.package').addHandler(plog)

    configurelog = logging.FileHandler(join(root,prefix+'_configure.log'),'w')
    configurelog.setFormatter(logf)
    configurelog.propagate=False
    logging.getLogger('ksl.installer.package.configure').addHandler(configurelog)

    patchlog = logging.FileHandler(join(root,prefix+'_patch.log'),'w')
    patchlog.setFormatter(logf)
    patchlog.propagate=False
    logging.getLogger('ksl.installer.package.patch').addHandler(patchlog)

    makelog = logging.FileHandler(join(root,prefix+'_make.log'),'w')
    makelog.setFormatter(logf)
    makelog.propagate=False
    logging.getLogger('ksl.installer.package.make').addHandler(makelog)

    log = logging.getLogger('ksl.installer')
    log.info('logging install for variant %s to %s' % (variant.variant_id, logname))

    return [(plog, 'ksl.installer.package'),
            (configurelog, 'ksl.installer.package.configure'),
            (patchlog, 'ksl.installer.package.patch'),
            (makelog, 'ksl.installer.package.make')]

def close_logs(logs):
    for handle, logname in logs:
        handle.flush()
        handle.close()
        logging.getLogger(logname).removeHandler(handle)
    return

def parse_install_file(options, args):
    log = logging.getLogger('ksl.installer')
    
    installfile = string.join(args)
    if not os.path.exists(installfile):
        raise Exception("couldn't locate install file: %s" % installfile)

    log.info("parsing install file %s" % installfile)

    execfile(installfile,globals())
    for variant in variants:
        variant.root = options.root
        variant.source_paths = options.source_paths
        variant.patch_paths = options.patch_paths
        variant.build_dir = options.build_dir
        variant.module_cmd = options.module_cmd

    return variants

if __name__ == "__main__":
    try:
        main()
    except:
        print \
"""There was some sort of error running the script
Please report to Aron Ahmadia <aron.ahmadia@kaust.edu.sa>"""
        raise

