#!/usr/bin/env python

import os
import re
import sys
import select
import subprocess
import logging
from optparse import OptionParser
import time
import string

def main():
    parser = OptionParser()
    parser.add_option("-v", "--verbose",
                      action="store_true", dest="verbose", default=False,
                      help="print informational status messages to stdout")
    parser.add_option("-d", "--debug",
                      action="store_true", dest="debug", default=False)
    parser.add_option("-r", "--root",
                      action="store", dest="root", default="/opt/share/ksl",
                      help="root directory to install to (default: /opt/share/ksl)")

    (options, args) = parser.parse_args()

    if options.debug:
        logging.basicConfig(level=logging.DEBUG,
                            format='%(asctime)s %(levelname)s %(message)s')
    elif options.verbose:
        logging.basicConfig(level=logging.INFO,
                            format='%(asctime)s %(levelname)s %(message)s')
    else:
        logging.basicConfig(level=logging.WARNING,
                            format='%(asctime)s %(levelname)s %(message)s')

    logger = logging.getLogger('ksl_install')

    logger.info("attempting to delete old pipes")

if __name__ == "__main__":
    try:
        main()
    except:
        print \
"""There was some sort of error running the script
Please report to Aron Ahmadia <aron.ahmadia@kaust.edu.sa>"""
        raise
